# Jekyll 配置文件
title: "Xiaochen Zhang's Homepage"
author: "Xiaochen Zhang"
email: "zhangxiaochenruby166@outlook.com"
description: "Advancing the frontier of statistics and machine learning."
theme: minima  # 你也可以换成其他 GitHub Pages 支持的主题
baseurl: ""
url: "https://rubyz​hang166.github.io"

# 主页显示文章
show_excerpts: true
header_pages:
  - about.md
  - research.md
  - publications.md
  - contact.md

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
